# Generated by Django 3.2 on 2021-06-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarista',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
