# Generated by Django 3.2 on 2021-06-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_diarista_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarista',
            name='foto_usuario',
            field=models.ImageField(upload_to=''),
        ),
    ]
