# Generated by Django 3.2 on 2021-06-16 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_diarista_foto_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarista',
            old_name='telefone',
            new_name='telefon',
        ),
    ]
