# Generated by Django 3.2 on 2021-06-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_diarista_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarista',
            name='cidade',
            field=models.CharField(max_length=30),
        ),
    ]
